#!/bin/bash -eu
# Copyright 2016 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
################################################################################


# afl needs its special coverage flags

echo "Checking out aflgo .."
pushd $SRC >/dev/null
git clone  https://github.com/aflgo/aflgo.git
cd aflgo
git checkout c9efa4f
cd ..
cd aflgo && CFLAGS="" CXXFLAGS="" make
cd llvm_mode && CFLAGS="" CXXFLAGS="" make
popd > /dev/null


rm -rf $WORK/afl

echo " done."
